# Sealos Secrets 模板
# 
# 使用说明:
# 1. 复制此文件为 secrets.yaml (不要提交到 Git)
# 2. 替换所有 CHANGE_ME_* 占位符为实际值
# 3. 使用 kubectl apply -f secrets.yaml 应用配置
#
# 注意: secrets.yaml 已在 .gitignore 中，不会被提交

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tdd-ma
type: Opaque
stringData:
  username: "root"
  password: "CHANGE_ME_MYSQL_PASSWORD"           # 修改为强密码，如: MyS3cr3tP@ssw0rd!2024
  root-password: "CHANGE_ME_MYSQL_ROOT_PASSWORD" # 修改为强密码，如: R00tP@ssw0rd!2024

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: tdd-ma
type: Opaque
stringData:
  password: "CHANGE_ME_REDIS_PASSWORD"           # 修改为强密码，如: R3d!sP@ssw0rd!2024

---
# 应用配置 Secret (可选)
# 如果需要更多环境变量配置，可以在这里添加
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: tdd-ma
type: Opaque
stringData:
  # 外部服务 API Key (如果需要)
  audience-service-api-key: "CHANGE_ME_API_KEY"
  
  # JWT Secret (如果使用 JWT 认证)
  jwt-secret: "CHANGE_ME_JWT_SECRET"
  
  # 其他敏感配置
  # ...

---
# 应用配置 ConfigMap (非敏感配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tdd-ma
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "prod"
  
  # 外部服务 URL
  AUDIENCE_SERVICE_URL: "https://api.example.com"
  
  # 时区
  TZ: "Asia/Shanghai"
  
  # 日志级别
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_TDD_MA: "DEBUG"
  
  # JVM 参数
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -Xms512m -Xmx1024m"
