# 外部数据库配置模板
# 
# 使用说明:
# 1. 复制此文件为 external-db-secret.yaml (不要提交到 Git)
# 2. 替换所有占位符为实际的外部数据库连接信息
# 3. 使用 kubectl apply -f external-db-secret.yaml 应用配置
#
# 注意: external-db-secret.yaml 已在 .gitignore 中，不会被提交

---
apiVersion: v1
kind: Secret
metadata:
  name: external-db-secret
  namespace: tdd-ma
type: Opaque
stringData:
  # MySQL 配置
  mysql-url: "jdbc:mysql://YOUR_MYSQL_HOST:3306/marketing_automation?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8"
  # 示例: jdbc:mysql://mysql.example.com:3306/marketing_automation?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  
  mysql-username: "YOUR_MYSQL_USERNAME"
  # 示例: root 或 your_db_user
  
  mysql-password: "YOUR_MYSQL_PASSWORD"
  # 示例: YourStrongPassword123!
  
  # Redis 配置
  redis-host: "YOUR_REDIS_HOST"
  # 示例: redis.example.com 或 10.0.0.100
  
  redis-port: "6379"
  # 通常是 6379
  
  redis-password: "YOUR_REDIS_PASSWORD"
  # 如果 Redis 没有密码，可以设置为空字符串: ""
  # 示例: YourRedisPassword123!

---
# 应用配置 ConfigMap (非敏感配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tdd-ma
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "prod"
  
  # 外部服务 URL
  AUDIENCE_SERVICE_URL: "https://api.example.com"
  
  # 时区
  TZ: "Asia/Shanghai"
  
  # 日志级别
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_TDD_MA: "DEBUG"
  
  # JVM 参数
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -Xms512m -Xmx1024m"
